---
kind: Service
apiVersion: v1
metadata:
  name: gw-public
spec:
  selector:
    app: gw-public
  ports:
  - port: 8000
    nodePort: 32600
    name: web
  - port: 8080
    nodePort: 32680
    name: admin
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: gw-public
  labels:
    app: gw-public
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gw-public
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - gw-public
              topologyKey: kubernetes.io/hostname
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 30
      containers:
      - name: gw-public
        image: zing-traefik
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 512
        args:
        - --web
        - --kubernetes
        - --kubernetes.labelselector=public-api=true
        - --loglevel=INFO
        - --insecureSkipVerify=true
        ports:
        - containerPort: 8000
          name: web
        - containerPort: 8080
          name: admin
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 20Mi
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gw-public
spec:
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gw-public
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: gw-public-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: gw-public

