kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: gw-private-ingress-controller-traefik
  labels:
    k8s-app: gw-private-ingress-lb
spec:
  selector:
    matchLabels:
      k8s-app: gw-private-ingress-lb-traefik
      name: gw-private-ingress-lb-traefik
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: gw-private-ingress-lb-traefik
        name: gw-private-ingress-lb-traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      nodeSelector:
        ilb-pool: "true"
      tolerations:
        - key: "ilb-pool"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
      - image: zing-traefik
        name: gw-private-ingress-lb-traefik
        ports:
        - name: http
          containerPort: 8000
          hostPort: 80
        - name: admin
          containerPort: 8080
          hostPort: 50080
        securityContext:
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
          runAsUser: 512
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --kubernetes.labelselector=traefik-private-api=true
        resources:
          requests:
            memory: 750M
