apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
---
apiVersion: v1
kind: Service
metadata:
  name: gw-public
spec:
  ports:
  - name: web
    nodePort: 32600
    port: 8000
  - name: admin
    nodePort: 32680
    port: 8080
  selector:
    app: gw-public
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: gw-public
  name: gw-public
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gw-public
    spec:
      containers:
      - args:
        - --web
        - --kubernetes
        - --kubernetes.labelselector=public-api=true
        - --loglevel=INFO
        - --insecureSkipVerify=true
        image: zing-traefik
        name: gw-public
        ports:
        - containerPort: 8000
          name: web
        - containerPort: 8080
          name: admin
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 512
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 30
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: gw-private-ingress-lb
  name: gw-private-ingress-controller-traefik
spec:
  template:
    metadata:
      labels:
        k8s-app: gw-private-ingress-lb-traefik
        name: gw-private-ingress-lb-traefik
    spec:
      containers:
      - args:
        - --api
        - --kubernetes
        - --logLevel=INFO
        - --kubernetes.labelselector=traefik-private-api=true
        image: zing-traefik
        name: gw-private-ingress-lb-traefik
        ports:
        - containerPort: 80
          hostPort: 80
          name: http
        - containerPort: 8080
          hostPort: 50080
          name: admin
        resources:
          limits:
            memory: 1.5G
          requests:
            memory: 1G
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
      nodeSelector:
        ilb-pool: "true"
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      tolerations:
      - effect: NoSchedule
        key: ilb-pool
        operator: Equal
        value: "true"
  updateStrategy:
    type: RollingUpdate
